repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.5.6'
    hooks:
        - id: ruff
          args:
            - --fix
        - id: ruff-format
          args:
           - --config=pyproject.toml

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.11.1
      hooks:
      -   id: mypy
          additional_dependencies:
          - types-all